CREATE DATABASE QLY_CTY

USE QLY_CTY

CREATE TABLE NHAN_VIEN(
	MA_NV VARCHAR(5) NOT NULL,
	HO_NV NVARCHAR(20) NOT NULL,
	TEN_NV NVARCHAR(20) NOT NULL,
	MA_PHG VARCHAR(5) NOT NULL,
	TUOI INT NOT NULL,
	LUONG DECIMAL(18,0) NOT NULL,
)

CREATE TABLE PHONG(
	MA_PHG VARCHAR(5) NOT NULL,
	MA_CTY VARCHAR(5) NOT NULL,
	TEN_PHG NVARCHAR(20) NOT NULL,
	LOAI_PHG NVARCHAR(20) NOT NULL,
	SOLUONG_NV INT NOT NULL,
	TEN_TRUONGPHONG NVARCHAR(50) NOT NULL,
	DIADIEM NVARCHAR(50) NOT NULL,
)

CREATE TABLE CONG_TY(
	MA_CTY VARCHAR(5) NOT NULL,
	TEN_CTY NVARCHAR(50) NOT NULL,
	NGAY_THANHLAP DATE NOT NULL,
)

ALTER TABLE NHAN_VIEN
ADD CONSTRAINT PK_NHAN_VIEN
PRIMARY KEY (MA_NV)

ALTER TABLE PHONG
ADD CONSTRAINT PK_PHONG
PRIMARY KEY (MA_PHG)

ALTER TABLE CONG_TY
ADD CONSTRAINT PK_CONG_TY
PRIMARY KEY (MA_CTY)

ALTER TABLE PHONG
ADD CONSTRAINT FK_MA_CTY
FOREIGN KEY (MA_CTY) REFERENCES CONG_TY (MA_CTY);

ALTER TABLE NHAN_VIEN
ADD CONSTRAINT FK_MA_PHG
FOREIGN KEY (MA_PHG) REFERENCES PHONG (MA_PHG);

ALTER TABLE NHAN_VIEN
ADD CONSTRAINT CK_TUOI CHECK (TUOI >=18 AND TUOI <=64),
	CONSTRAINT CK_LUONG CHECK (LUONG >=0);
	
ALTER TABLE PHONG
ADD CONSTRAINT CK_SOLUONG CHECK (SOLUONG_NV >= 0);

ALTER TABLE CONG_TY
ADD CONSTRAINT CK_NGAY_THANHLAP CHECK (NGAY_THANHLAP < CAST (GETDATE () AS DATE ));

INSERT INTO CONG_TY (MA_CTY, TEN_CTY, NGAY_THANHLAP) VALUES
('CT001', N'Công ty ISOVN', '2010-05-01'),
('CT002', N'Công ty TechGen', '2015-09-12'),
('CT003', N'Công ty Xanh Sạch', '2018-03-20');

INSERT INTO PHONG (MA_PHG, MA_CTY, TEN_PHG, LOAI_PHG, SOLUONG_NV, TEN_TRUONGPHONG, DIADIEM) VALUES
('P001', 'CT001', N'Phòng Hành Chính', N'Văn phòng', 5, N'Nguyễn Văn An', N'Tầng 3 - Trụ sở chính'),
('P002', 'CT001', N'Phòng Kỹ Thuật', N'Kỹ thuật', 8, N'Lê Thị Bình', N'Tầng 4 - Tòa nhà ISOVN'),
('P003', 'CT002', N'Phòng Kế Toán', N'Tài chính', 4, N'Trần Văn Cường', N'Văn phòng TP.HCM'),
('P004', 'CT003', N'Phòng Marketing', N'Truyền thông', 6, N'Phạm Thị Dung', N'Tầng 2 - Cơ sở Hà Nội');

INSERT INTO NHAN_VIEN (MA_NV, HO_NV, TEN_NV, MA_PHG, TUOI, LUONG) VALUES
('NV001', N'Nguyễn', N'Thành', 'P001', 29, 12000000),
('NV002', N'Lê', N'Quỳnh', 'P001', 34, 11000000),
('NV003', N'Phạm', N'Tú', 'P002', 27, 15000000),
('NV004', N'Trần', N'An', 'P002', 31, 14500000),
('NV005', N'Hoàng', N'Mai', 'P003', 26, 10000000),
('NV006', N'Vũ', N'Thảo', 'P003', 39, 12500000),
('NV007', N'Đặng', N'Linh', 'P004', 30, 13000000),
('NV008', N'Bùi', N'Trung', 'P004', 28, 12800000);

CREATE VIEW VIEW_HOTEN_PHG AS
SELECT 
    NV.HO_NV,
    NV.TEN_NV,
    P.TEN_PHG,
    P.DIADIEM
FROM NHAN_VIEN NV
JOIN PHONG P ON NV.MA_PHG = P.MA_PHG;

SELECT * FROM VIEW_HOTEN_PHG

CREATE VIEW NHANVIEN_CTY AS
SELECT 
	NV.HO_NV + ' ' + NV.TEN_NV AS HOTEN,
	NV.LUONG,
	NV.TUOI
FROM NHAN_VIEN NV

SELECT * FROM NHANVIEN_CTY

CREATE VIEW VIEW_PHG_DONGNV AS
SELECT TOP 1
	P.TEN_PHG,
	P.TEN_TRUONGPHONG,
	P.SOLUONG_NV
FROM PHONG P
ORDER BY P.SOLUONG_NV DESC

SELECT * FROM VIEW_PHG_DONGNV