CREATE DATABASE QLY_DUAN
GO

USE QLY_DUAN
GO

CREATE TABLE NHAN_VIEN(
    ID_NHANVIEN INT NOT NULL,
    HO_NV NVARCHAR(20) NOT NULL,
    TEN_NV NVARCHAR(20) NOT NULL,
    NGAY_SINH DATE,
    LUONG FLOAT NULL,
    PHG CHAR(5) NULL
);
GO

CREATE TABLE PHONG_BAN(
    MA_PB CHAR(5) NOT NULL PRIMARY KEY,
    TEN_PB NVARCHAR(30) NOT NULL,
    MOTA NVARCHAR(50)
);
GO

CREATE TABLE DUAN(
    Ma_DA VARCHAR(5) PRIMARY KEY NOT NULL,
    Ten_DA NVARCHAR(50),
    NgayKhoiCong DATE,
    NgayKetThuc DATE,
    MoTA NVARCHAR(100)
);
GO

CREATE TABLE CTDA (
    Ma_NV INT NOT NULL,
    Ma_DA VARCHAR(5) NOT NULL,
    mota NVARCHAR(100)
);
GO

-- Thêm cột GIOITINH
ALTER TABLE NHAN_VIEN ADD GIOITINH BIT;
GO
ALTER TABLE NHAN_VIEN
ADD CONSTRAINT PK
PRIMARY KEY (ID_NHANVIEN);

ALTER TABLE DUAN
ADD CONSTRAINT PK_DUAN
PRIMARY KEY (MA_DA);

ALTER TABLE PHONG_BAN
ADD CONSTRAINT 

-- Ràng buộc mức lương
ALTER TABLE NHAN_VIEN
ADD CONSTRAINT CHK_MUCLUONG_MIN
CHECK (LUONG >= 1000);



-- Khóa chính
ALTER TABLE NHAN_VIEN
ADD CONSTRAINT PKEY_NHANVIEN PRIMARY KEY (ID_NHANVIEN);
GO

-- Khóa ngoại PHG → PHONG_BAN
ALTER TABLE NHAN_VIEN
ADD CONSTRAINT FKEY_NV_PB
FOREIGN KEY (PHG) REFERENCES PHONG_BAN(MA_PB);
GO

-- Khóa chính bảng CTDA
ALTER TABLE CTDA
ADD CONSTRAINT PK_CTDA PRIMARY KEY (Ma_NV, Ma_DA);
GO

-- Dữ liệu PHONG_BAN
INSERT INTO PHONG_BAN VALUES 
('PB001','CNTT',NULL),
('PB002','HR',NULL),
('PB003','KETOAN',NULL),
('PB004','DIGITAL',NULL),
('PB005','MARKETING',NULL),
('PB006','HOP',NULL),
('PB007','BUSS',NULL),
('PB008','TRUYEN THONG',NULL),
('PB009','HANH CHINH',NULL);
GO

-- Dữ liệu DUAN
INSERT INTO DUAN VALUES 
('DA001','TRONGCAY','2025-2-26','2025-3-30',NULL),
('DA002','XAY CAU','2025-1-12','2025-4-20',NULL),
('DA003','XAY NHA','2025-8-13','2025-9-10',NULL),
('DA004','DAO HAM','2025-12-9','2026-1-02',NULL),
('DA005','MO RONG DO THI','2026-3-20','2026-5-27',NULL);
GO

-- Dữ liệu NHAN_VIEN
INSERT INTO NHAN_VIEN (ID_NHANVIEN, HO_NV, TEN_NV, NGAY_SINH, LUONG, PHG, GIOITINH) VALUES
(1,'NGUYEN','ANH DUONG','2006-02-09',10000000,'PB002',0),
(2,'NGUYEN','DUC ANH','2007-12-19',1000000,'PB003',0),
(3,'PHAM','TRUNG KIEN','2006-06-20',16000000,'PB001',1),
(4,'LE','HOANG ANH','2007-08-02',20000000,'PB001',0),
(5,'LE','MINH NGOC','2006-02-28',13000000,'PB007',1);
GO
INSERT INTO CTDA (Ma_NV, Ma_DA, mota) VALUES
(1, 'DA001', N'Tham gia trồng cây'),
(2, 'DA002', N'Phụ trách vận hành máy móc thi công cầu'),
(3, 'DA003', N'Giám sát kỹ thuật xây nhà'),
(4, 'DA004', N'Kỹ sư đào hầm'),
(5, 'DA005', N'Thiết kế mở rộng đô thị'),
(1, 'DA003', N'Hỗ trợ kỹ thuật xây nhà'),
(2, 'DA005', N'Tham gia khảo sát địa chất'),
(3, 'DA001', N'Tư vấn quy trình trồng cây');
-- Cập nhật tên phòng ban
UPDATE PHONG_BAN SET TEN_PB = 'HANH CHINH' WHERE MA_PB='PB009';

-- Xóa phòng ban (nếu muốn)
DELETE FROM PHONG_BAN WHERE TEN_PB = 'HANH_CHINH'; -- Lưu ý: khác dấu gạch dưới
GO

-- Truy vấn thông tin nhân viên và phòng ban
SELECT NV.ID_NHANVIEN, NV.TEN_NV, NV.PHG, PB.MA_PB, PB.TEN_PB
FROM NHAN_VIEN NV
JOIN PHONG_BAN PB ON NV.PHG = PB.MA_PB;
GO

-- Truy vấn thông tin nhân viên và dự án
SELECT NV.ID_NHANVIEN, NV.HO_NV, NV.TEN_NV, DA.NgayKhoiCong, DA.NgayKetThuc
FROM CTDA CT
JOIN DUAN DA ON CT.Ma_DA = DA.Ma_DA
JOIN NHAN_VIEN NV ON CT.Ma_NV = NV.ID_NHANVIEN;
GO

SELECT * FROM NHAN_VIEN
WHERE LUONG > (SELECT AVG(LUONG) FROM NHAN_VIEN)

SELECT NV.ID_NHANVIEN, NV.HO_NV,NV.TEN_NV,NV.NGAY_SINH,NV.LUONG,NV.PHG,NV.GIOITINH
FROM NHAN_VIEN NV
JOIN PHONG_BAN PB ON PB.MA_PB =NV.PHG
WHERE PB.TEN_PB = 'UDPM'

CREATE VIEW NV_NHANVIEN AS
SELECT ID_NHANVIEN,HO_NV,TEN_NV, GIOITINH, PHG
FROM NHAN_VIEN

SELECT * FROM NV_NHANVIEN

DROP VIEW NV_NHANVIEN

CREATE VIEW VW_PHONGBAN_NHANVIEN
AS
SELECT TOP 1
	PB.TEN_PB,
	NV.HO_NV+' ' +NV.TEN_NV AS TRUONGPHONG,
	COUNT (NV.ID_NHANVIEN) AS 'SO NV'
FROM PHONG_BAN PB
JOIN NHAN_VIEN NV ON PB.MA_PB =NV.PHG
GROUP BY PB.TEN_PB, NV.HO_NV,NV.TEN_NV
ORDER BY COUNT (NV.ID_NHANVIEN) DESC;

SELECT * FROM VW_PHONGBAN_NHANVIEN

UPDATE NV_NHANVIEN
SET PHG = 'IT';

INSERT INTO NV_NHANVIEN (
	[ID_NHANVIEN],
	[HO_NV],
	[TEN_NV],
	[GIOITINH],
	[PHG])
	VALUES (13,'HOANG','QUOC VIET','1','UDPM');

DELETE FROM NV_NHANVIEN 
	WHERE ID_NHANVIEN = 12;

CREATE PROC SP_TONG
	@SO1 INT, @SO2 INT
	AS 
	BEGIN
		DECLARE @TONG INT
		SET @TONG = @SO1 + @SO2
		PRINT @TONG
	END

	EXEC SP_TONG 34,21

CREATE PROC SP_TONG_TINH
	@TENSP NVARCHAR(20)

CREATE PROC SPTONG
	@SO1 INT, @SO2 INT, @TONG INT OUT
	AS
	BEGIN 
		SET @TONG = @SO1 + @SO2
	END


	DECLARE @SUM INT
	EXEC SPTONG 23,16, @SUM OUT
	SELECT @SUM


CREATE PROC SOLUONG_NV
	@GTINH NVARCHAR(3)
	AS 
	BEGIN
		DECLARE @NUM INT
		SELECT @NUM = COUNT(*) FROM NHAN_VIEN
		WHERE GIOITINH LIKE '%' + @GTINH
		RETURN @NUM;
	END

	DECLARE @TONG INT 
	EXEC @TONG = SOLUONG_NV '1'
	SELECT @TONG;

CREATE PROC THONGTIN_NV
	@MANV NVARCHAR(9)
	AS 
	BEGIN 
		SELECT * FROM NHAN_VIEN WHERE ID_NHANVIEN =@MANV
	END

	EXEC THONGTIN_NV '1'
	SELECT * FROM NHAN_VIEN

CREATE PROC SP_THEMPHONGBAN
@MAPHONG CHAR(5), @TENPHONG NVARCHAR(15)
AS
BEGIN
	IF EXISTS (SELECT * FROM PHONG_BAN WHERE MA_PB = @MAPHONG)
		BEGIN 
			UPDATE PHONG_BAN
			SET TEN_PB = @TENPHONG
			WHERE MA_PB = @MAPHONG
		END
	ELSE
		BEGIN
			INSERT INTO PHONG_BAN(MA_PB,TEN_PB) VALUES (@MAPHONG,@TENPHONG)
		END
	END

	EXEC SP_THEMPHONGBAN 'PB222','PTPM_UDPM'

ALTER PROC SP_THEMPHONGBAN
@MAPHONG CHAR(5), @TENPHONG NVARCHAR(15), @MOTA NVARCHAR(255)
AS
BEGIN
	IF EXISTS (SELECT * FROM PHONG_BAN WHERE MA_PB = @MAPHONG)
		BEGIN 
			UPDATE PHONG_BAN
			SET TEN_PB = @TENPHONG,
				MOTA = @MOTA
			WHERE MA_PB = @MAPHONG
		END
	ELSE
		BEGIN
			INSERT INTO PHONG_BAN(MA_PB,TEN_PB,MOTA) VALUES (@MAPHONG,@TENPHONG,@MOTA)
		END
	END

	EXEC SP_THEMPHONGBAN 'PB222','PTPM_UDPM'
