CREATE CLUSTERED INDEX idx_NhanVien_ID
ON NHAN_VIEN (ID_NHANVIEN);

CREATE NONCLUSTERED INDEX idx_NhanVien_HoTen
ON NHAN_VIEN (TEN_NV);

CREATE NONCLUSTERED INDEX idx_QuanLyDuAn_MaNhan_Vien_MaDuAn
ON QUANLY_DUAN (MA_NHANVIEN,MA_DUAN);

CREATE UNIQUE INDEX idx_PhongBan_TenPB
ON PHONG_BAN (TEN_PB);

CREATE FULLTEXT INDEX ON NHANVIEN (TEN_NV)
KEY INDEX idx_NhanVien_ID

CREATE TRIGGER CHECK_LUONG_NV ON NHANVIEN FOR INSERT AS
IF (SELECT LUONG FROM inserted) <5000
BEGIN
PRINT 'Tien luong toi thieu phai lon hon 5000.'
ROLLBACK TRANSACTION
END

CREATE TRIGGER CHECK_LUONG_NV ON NHANVIEN FOR UPDATE AS
IF (SELECT LUONG FROM inserted) <5000
BEGIN
PRINT 'Tien luong toi thieu phai lon hon 5000.'
ROLLBACK TRANSACTION
END

UPDATE NHANVIEN SET LUONG = 2000 WHERE MANV LIKE '005'

CREATE TRIGGER XOANV
ON NHANVIEN
FOR DELETE
IF '005' IN (SELECT MANV FROM DELETE)
BEGIN
PRINT 'KHONG THE XOA BAN GHI NAY'
ROLLBACK TRANSACTION 
END

CREATE TRIGGER XOA_NV
ON NHANVIEN
AFTER DELETE 
AS
BEGIN
DECLARE @NUM NCHAR;
SELECT @NUM = COUNT(*) FROM deleted
PRINT N'SO LUONG NHAN VIEN DA XOA = ' + @NUM
END

ALTER TABLE NHANVIEN DROP CONSTRAINT FK_PHG
CREATE TABLE BKUP_PHONGBAN (
	MA_PB CHAR(5),
	TEN_PB NVARCHAR(20),
	MOTA NVARCHAR(50)
)

CREATE TRIGGER TRG_PHONGBAN_DELETED ON PHONGBAN
AFTER DELETE
AS 
BEGIN
	INSERT INTO BKUP_PHONGBAN (MA_PB,TEN_PB,MOTA)
	SELECT MA_PB,TEN,PB,MOTA DELETED;
END;

DELETE FROM PHONG_BAN WHERE MA_PB = 'PB500'
SELECT * FROM BKUP_PHONGBAN