CREATE DATABASE QLY_SANPHAM

USE QLY_SANPHAM

CREATE TABLE LOAI (
	MA_LOAI VARCHAR(5) NOT NULL,
	TEN_LOAI VARCHAR (5) NOT NULL,
)

CREATE TABLE SAN_PAHM (
	MA_SP VARCHAR(5) NOT NULL,
	TEN_SP NVARCHAR(50) NOT NULL,
	MA_LOAI VARCHAR(5) NOT NULL,
)

CREATE TABLE NHAN_VIEN(
	MA_NV VARCHAR(5) NOT NULL,
	HO_TEN NVARCHAR(50) NOT NULL,
	NGAY_SINH DATE NOT NULL,
	GT NVARCHAR(10) NOT NULL,
)

CREATE TABLE PHIEU_XUAT(
	MA_PX VARCHAR(5) NOT NULL,
	NGAY_LAP DATE NOT NULL,
	MA_NV VARCHAR(5) NOT NULL,
)

CREATE TABLE CHITIET_PHIEUXUAT (
	MA_PX VARCHAR(5) NOT NULL,
	MA_SP VARCHAR(5) NOT NULL,
	SO_LUONG INT NOT NULL,
)

ALTER TABLE LOAI 
ADD CONSTRAINT PK_LOAI
PRIMARY KEY (MA_LOAI)

EXEC SP_RENAME 'SAN_PAHM','SAN_PHAM';

ALTER TABLE SAN_PHAM
ADD CONSTRAINT PK_SP
PRIMARY KEY (MA_SP)

ALTER TABLE NHAN_VIEN
ADD CONSTRAINT PK_NHAN_VIEN
PRIMARY KEY (MA_NV)

ALTER TABLE PHIEU_XUAT
ADD CONSTRAINT PK_PX
PRIMARY KEY (MA_PX)

ALTER TABLE CHITIET_PHIEUXUAT
ADD CONSTRAINT PK_CT_PX
PRIMARY KEY (MA_PX,MA_SP)

ALTER TABLE NHAN_VIEN
ADD CONSTRAINT CK_NGAY_SINH
CHECK ( NGAY_SINH < CAST(GETDATE() AS DATE));

ALTER TABLE CHITIET_PHIEUXUAT
ADD CONSTRAINT CK_SO_LUONG
CHECK (SO_LUONG >=0)

ALTER TABLE PHIEU_XUAT
ADD CONSTRAINT CK_NGAY_LAP
CHECK (NGAY_LAP >= CAST (GETDATE () AS DATE));

ALTER TABLE PHIEU_XUAT
ADD CONSTRAINT FK_MA_NV
FOREIGN KEY (MA_NV) REFERENCES NHAN_VIEN (MA_NV)

ALTER TABLE CHITIET_PHIEUXUAT
ADD CONSTRAINT FK_MA_PX
FOREIGN KEY (MA_PX) REFERENCES PHIEU_XUAT (MA_PX)

ALTER TABLE CHITIET_PHIEUXUAT
ADD CONSTRAINT FK_MA_SP
FOREIGN KEY (MA_SP) REFERENCES SAN_PHAM (MA_SP)

ALTER TABLE SAN_PHAM
ADD CONSTRAINT FK_MA_LOAI
FOREIGN KEY (MA_LOAI) REFERENCES LOAI (MA_LOAI)