CREATE DATABASE QL_KINHDOANH

USE QL_KINHDOANH

CREATE TABLE NHAN_VIEN (
	MA_NV VARCHAR(5) NOT NULL,
	HO NVARCHAR (10) NOT NULL,
	TEN NVARCHAR(20) NOT NULL,
	NGAY_SINH DATE NOT NULL,
	NGAY_LAMVIEC DATE NOT NULL,
	DIA_CHI NVARCHAR(225) NOT NULL,
	DIENTHOAI INT NOT NULL,
	LUONG_COBAN DECIMAL (10,2) NOT NULL,
	PHU_CAP DECIMAL (10,2)NOT NULL,
)

CREATE TABLE KHACH_HANG (
	MA_KH VARCHAR(5) NOT NULL,
	TEN_CT NVARCHAR(50) NOT NULL,
	TEN_GD NVARCHAR(50) NOT NULL,
	DIA_CHI NVARCHAR(225) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	DIEN_THOAI INT NOT NULL,
	FAX VARCHAR(20) NOT NULL,
	)
CREATE TABLE LOAI_HANG (
	MA_LOAIHANG VARCHAR(5) NOT NULL,
	TEN_LOAIHANG NVARCHAR(50) NOT NULL,
)

CREATE TABLE NHA_CUNGCAP(
	MA_CTY VARCHAR(5) NOT NULL,
	TEN_CTY NVARCHAR(50) NOT NULL,
	TEN_GD NVARCHAR(50) NOT NULL,
	DIA_CHI NVARCHAR(225) NOT NULL,
	DIEN_THOAI INT NOT NULL,
	FAX VARCHAR(20) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
)

CREATE TABLE DON_DATHANG(
	SO_HOADON VARCHAR(5) NOT NULL,
	MA_KH VARCHAR(5) NOT NULL,
	MA_NV VARCHAR(5) NOT NULL,
	NGAY_DATHANG DATE NOT NULL,
	NGAY_GIAOHANG DATE NOT NULL,
	NGAY_CHUYENHANG DATE NOT NULL,
	NOI_GIAOHANG NVARCHAR(225) NOT NULL,
)

CREATE TABLE MATHANG (
	MA_HANG VARCHAR(5) NOT NULL,
	TEN_HANG NVARCHAR(50) NOT NULL,
	MA_CTY VARCHAR(5) NOT NULL,
	MA_LOAIHANG VARCHAR(5) NOT NULL,
	SOLUONG INT NOT NULL,
	DONVITINH VARCHAR (5) NOT NULL,
	GIAHANG DECIMAL(10,2) NOT NULL,
)

CREATE TABLE CHITIET_DATHANG (
	SO_HOADON VARCHAR(5) NOT NULL,
	MAHANG VARCHAR(5) NOT NULL,
	GIABAN DECIMAL(10,2) NOT NULL,
	SOLUONG INT NOT NULL,
	MUCGIAM_GIA VARCHAR(10)
)

ALTER TABLE DON_DATHANG 
ADD CONSTRAINT PK_DON_DATHANG
PRIMARY KEY (SO_HOADON)

ALTER TABLE KHACH_HANG
ADD CONSTRAINT PK_KHACH_HANG
PRIMARY KEY (MA_KH)

ALTER TABLE LOAI_HANG
ADD CONSTRAINT PK_LOAI_HANG
PRIMARY KEY (MA_LOAIHANG)

ALTER TABLE MATHANG
ADD CONSTRAINT PK_MATHANG
PRIMARY KEY (MA_HANG)

ALTER TABLE NHA_CUNGCAP
ADD CONSTRAINT PK_NHA_CUNGCAP
PRIMARY KEY (MA_CTY)

ALTER TABLE NHAN_VIEN
ADD CONSTRAINT PH_NHAN_VIEN
PRIMARY KEY (MA_NV)

ALTER TABLE CHITIET_DATHANG
ADD CONSTRAINT PK_CHITIET_DATHANG
PRIMARY KEY (SO_HOADON,MAHANG)

ALTER TABLE CHITIET_DATHANG
ADD CONSTRAINT CK_MUCGIAM_GIA
CHECK (MUCGIAM_GIA >=0);

ALTER TABLE CHITIET_DATHANG
ADD CONSTRAINT CK_SOLUONG
CHECK (SOLUONG >= 0)		

ALTER TABLE CHITIET_DATHANG
ADD CONSTRAINT CK_GIABAN
CHECK (GIABAN >=0)

ALTER TABLE DON_DATHANG
ADD CONSTRAINT CK_NGAY_DATAHNG
CHECK (NGAY_DATHANG >= CAST(GETDATE() AS DATE));

ALTER TABLE DON_DATHANG
ADD CONSTRAINT CK_NGAY_GIAOHANG
CHECK (NGAY_GIAOHANG >= CAST (GETDATE() AS DATE));

ALTER TABLE DON_DATHANG
ADD CONSTRAINT CK_NGAY_CHUYENHANG
CHECK (NGAY_CHUYENHANG >= CAST (GETDATE() AS DATE));

ALTER TABLE NHAN_VIEN
ADD CONSTRAINT CK_NGAY_SINH
CHECK (NGAY_SINH <= CAST(GETDATE() AS DATE));

ALTER TABLE NHAN_VIEN
ADD CONSTRAINT CK_NGAY_LAMVIEC
CHECK (NGAY_LAMVIEC >= CAST(GETDATE () AS DATE));

ALTER TABLE NHAN_VIEN
ADD CONSTRAINT CK_LUONG_COBAN
CHECK (LUONG_COBAN > 0);

ALTER TABLE NHAN_VIEN
ADD CONSTRAINT CK_PHU_CAP
CHECK (PHU_CAP >= 0);

ALTER TABLE DON_DATHANG
ADD CONSTRAINT FK_MA_KH
FOREIGN KEY (MA_KH) REFERENCES KHACH_HANG (MA_KH);

ALTER TABLE DON_DATHANG
ADD CONSTRAINT FK_MA_NV
FOREIGN KEY (MA_NV) REFERENCES NHAN_VIEN (MA_NV);

ALTER TABLE CHITIET_DATHANG
ADD CONSTRAINT FK_SO_HOADON
FOREIGN KEY (SO_HOADON) REFERENCES DON_DATHANG (SO_HOADON);

ALTER TABLE CHITIET_DATHANG
ADD CONSTRAINT FK_MAHANG
FOREIGN KEY (MAHANG) REFERENCES MATHANG (MAHANG)

ALTER TABLE MATHANG
DROP CONSTRAINT PK_MATHANG

ALTER TABLE MATHANG
DROP COLUMN MA_HANG

ALTER TABLE MATHANG
ADD MAHANG VARCHAR(5) NOT NULL

ALTER TABLE MATHANG
ADD CONSTRAINT PK_MATHANG
PRIMARY KEY (MAHANG)

ALTER TABLE MATHANG
ADD CONSTRAINT FK_MACTY
FOREIGN KEY (MA_CTY) REFERENCES NHA_CUNGCAP (MA_CTY)

ALTER TABLE MATHANG
ADD CONSTRAINT FK_MA_LOAIHANG
FOREIGN KEY (MA_LOAIHANG) REFERENCES LOAI_HANG (MA_LOAIHANG)