CREATE DATABASE QLY_BDS

USE QLY_BDS

CREATE TABLE CTY_BDS (
	MA_CTY VARCHAR(5) NOT NULL,
	TEN_CTY NVARCHAR(225) NOT NULL,
	CHU_SO_HUU NVARCHAR(225) NOT NULL,
	DIA_CHI NVARCHAR(225) NOT NULL,
	SO_DT INT NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	LOAI_CTY NVARCHAR(50) NOT NULL,
	NGAY_THANH_LAP DATE 
)

CREATE TABLE VAN_PHONG (
	MA_VP VARCHAR(5) NOT NULL,
	TEN_VP NVARCHAR(225) NOT NULL,
	TRUONG_PHONG NVARCHAR(225) NOT NULL,
	LOAI_VP NVARCHAR(50),
	DIA_DIEM NVARCHAR(50),
	NGAY_THANH_LAP DATE,
	SO_LUONG_NV INT,
)

CREATE TABLE NHAN_VIEN (
	MA_NV VARCHAR(5) NOT NULL,
	MA_VP VARCHAR(5) NOT NULL ,
	TEN_NV NVARCHAR(225) NOT NULL,
	CHUC_VU NVARCHAR(50) NOT NULL,
	GT NVARCHAR(10) NOT NULL,
	TUOI INT NOT NULL,
	SDT INT NOT NULL,
	DIA_CHI NVARCHAR(225) NOT NULL,
	EMAIL VARCHAR(225) NOT NULL,
	NGAY_GIA_NHAP DATE NOT NULL,
)

CREATE TABLE THAN_NHAN (
	MA_TN VARCHAR(5) NOT NULL,
	MA_NV VARCHAR(5) NOT NULL,
	TEN_NT NVARCHAR(225) NOT NULL,
	GT NVARCHAR(10) NOT NULL,
	TUOI INT NOT NULL,
	MQH NVARCHAR(10) NOT NULL,
	SDT INT NOT NULL,
	DIA_CHI NVARCHAR(225) NOT NULL,
	EMAIL VARCHAR(225) NOT NULL,
)

CREATE TABLE CHU_SH_BDS (
	MA_CSH VARCHAR(5) NOT NULL,
	MA_BDS VARCHAR(5) NOT NULL,
	TEN_CSH NVARCHAR(225) NOT NULL,
	GT NVARCHAR(10) NOT NULL,
	TUOI INT NOT NULL,
	SDT INT NOT NULL,
	DIA_CHI NVARCHAR(225) NOT NULL,
	NGAY_SH_BDS DATE NOT NULL,
)

CREATE TABLE BDS (
	MA_BDS VARCHAR(5) NOT NULL,
	MA_CSH VARCHAR(5) NOT NULL,
	MA_VP VARCHAR(5) NOT NULL,
	LOAI_BDS NVARCHAR(50) NOT NULL,
	DIA_CHI NVARCHAR(225) NOT NULL,
	DIEN_TICH DECIMAL(10,2) NOT NULL,
	MOTA NVARCHAR(225),
)

CREATE TABLE VP (
	MA_VP VARCHAR(5) NOT NULL,
	TEN_VP NVARCHAR(225) NOT NULL,
	TRUONG_PHONG NVARCHAR(225) NOT NULL,
	LOAI_VP NVARCHAR(50) NOT NULL,
	DIA_DIEM NVARCHAR(225) NOT NULL,
	NGAY_TLAP DATE NOT NULL,
	SLG_NV INT NOT NULL,
)

CREATE TABLE HOP_DONG (
	MA_HD VARCHAR(5) NOT NULL,
	MA_KH VARCHAR(5) NOT NULL,
	MA_NV VARCHAR(5) NOT NULL,
	MA_CT_GD VARCHAR(5) NOT NULL,
	TEN_HD NVARCHAR(225) NOT NULL,
	LOAI_DH NVARCHAR(50) NOT NULL,
	NGAY_KI_HD DATE NOT NULL,
	NGAY_HD_CO_HL DATE NOT NULL,
)

CREATE TABLE CT_GD (
	MA_GD VARCHAR(5) NOT NULL,
	MA_HD VARCHAR(5) NOT NULL,
	MA_KH VARCHAR(5) NOT NULL,
	MA_BDS VARCHAR(5) NOT NULL,
	LOAI_GD NVARCHAR(50) NOT NULL,
	DON_GIA DECIMAL(15,2) NOT NULL,
	TONG_GT DECIMAL(15,2) NOT NULL,
	TINH_TRANG_GD NVARCHAR(50) NOT NULL,
	MOTA NVARCHAR(225),
)

CREATE TABLE KHACH_HANG (
	MA_KH VARCHAR(5) NOT NULL,
	TEN_KH NVARCHAR(225) NOT NULL,
	GT NVARCHAR(10) NOT NULL,
	TUOI INT NOT NULL,
	SO_DT INT NOT NULL,
	EMAIL VARCHAR(225) NOT NULL,
)


ALTER TABLE CTY_BDS
DROP COLUMN EMAIL

ALTER TABLE CTY_BDS
ADD EMAIL VARCHAR(225) NOT NULL

ALTER TABLE NHAN_VIEN 
ADD LUONG INT NOT NULL

ALTER TABLE VAN_PHONG 
ADD MA_CTY VARCHAR(5) NOT NULL

ALTER TABLE NHAN_VIEN 
ADD CONSTRAINT CK_LUONG
CHECK ( LUONG > 100000 )

ALTER TABLE NHAN_VIEN
ADD CONSTRAINT CK_TUOI
CHECK ( TUOI > 18 )

ALTER TABLE VAN_PHONG
ADD CONSTRAINT CK_SLY_NV
CHECK ( SO_LUONG_NV >=0 )

DROP TABLE VP;

ALTER TABLE BDS
ADD CONSTRAINT PK_BDS
PRIMARY KEY ( MA_BDS)

ALTER TABLE VAN_PHONG
ADD CONSTRAINT PK_VP
PRIMARY KEY (MA_VP)

ALTER TABLE KHACH_HANG
ADD CONSTRAINT PK_KH
PRIMARY KEY (MA_KH)

ALTER TABLE NHAN_VIEN
ADD CONSTRAINT PK_NV
PRIMARY KEY (MA_NV)

ALTER TABLE THAN_NHAN
ADD CONSTRAINT PK_THAN_NHAN
PRIMARY KEY (MA_TN)

ALTER TABLE HOP_DONG
ADD CONSTRAINT PK_HD
PRIMARY KEY (MA_HD)

ALTER TABLE CT_GD
ADD CONSTRAINT PK_CT_GD
PRIMARY KEY (MA_GD)

ALTER TABLE CHU_SH_BDS
ADD CONSTRAINT PK_CSH
PRIMARY KEY (MA_CSH)

ALTER TABLE CTY_BDS
ADD CONSTRAINT PK_ATY_BDS
PRIMARY KEY (MA_CTY)

ALTER TABLE NHAN_VIEN
ADD CONSTRAINT FK_MA_VP
FOREIGN KEY (MA_VP) REFERENCES VAN_PHONG (MA_VP)

ALTER TABLE VAN_PHONG
ADD CONSTRAINT FK_MA_CTY
FOREIGN KEY (MA_CTY) REFERENCES CTY_BDS (MA_CTY)

ALTER TABLE THAN_NHAN
ADD CONSTRAINT FK_MA_TN
FOREIGN KEY (MA_NV) REFERENCES NHAN_VIEN (MA_NV)

ALTER TABLE CHU_SH_BDS
DROP COLUMN MA_BDS;

ALTER TABLE BDS
ADD CONSTRAINT FK_MA_CSH
FOREIGN KEY (MA_CSH) REFERENCES CHU_SH_BDS (MA_CSH)

ALTER TABLE BDS
ADD CONSTRAINT FK_MA_VP_BDS
FOREIGN KEY (MA_VP) REFERENCES VAN_PHONG (MA_VP)

ALTER TABLE HOP_DONG
ADD CONSTRAINT FK_MA_KH
FOREIGN KEY (MA_KH) REFERENCES KHACH_HANG (MA_KH)

ALTER TABLE HOP_DONG
ADD CONSTRAINT FK_MA_NV_HD
FOREIGN KEY (MA_NV) REFERENCES NHAN_VIEN (MA_NV)

ALTER TABLE HOP_DONG
ADD CONSTRAINT FK_MA_CT_GD
FOREIGN KEY (MA_GD) REFERENCES CT_GD (MA_GD)

ALTER TABLE CT_GD
ADD CONSTRAINT FK_MA_HD_GD
FOREIGN KEY (MA_HD) REFERENCES HOP_DONG (MA_HD)

ALTER TABLE CT_GD
ADD CONSTRAINT FK_MA_KH_GD
FOREIGN KEY (MA_KH) REFERENCES KHACH_HANG (MA_KH)

ALTER TABLE CT_GD
ADD CONSTRAINT FK_MA_BDS_GD
FOREIGN KEY (MA_BDS) REFERENCES BDS (MA_BDS)

