CREATE DATABASE QLY_NHANVIEN

USE QLY_NHANVIEN

CREATE TABLE NHANVIEN(
	MA_NHANVIEN VARCHAR(5) NOT NULL,
	HO_NHANVIEN NVARCHAR(20) NOT NULL,
	TEN_NHANVIEN NVARCHAR(20) NOT NULL,
	GIOITINH NVARCHAR(3) NOT NULL,
	TUOI INT NOT NULL,
	DIACHI NVARCHAR(50) NOT NULL,
	TONGSO_DA INT NOT NULL
)
ALTER TABLE NHANVIEN
ADD LUONG DECIMAL(18,0)

ALTER TABLE NHANVIEN
ADD CONSTRAINT PK_NHANVIEN PRIMARY KEY (MA_NHANVIEN);

CREATE TRIGGER NHANVIEN_INSERT_CHECK
ON NHANVIEN
AFTER INSERT
AS
BEGIN
	IF EXISTS (SELECT 1 FROM INSERTED WHERE LUONG <= 15000)
	 BEGIN
        RAISERROR (N'Lương phải lớn hơn 15000', 16, 1)
        ROLLBACK TRANSACTION
        RETURN
    END

	IF EXISTS (SELECT 1 FROM INSERTED WHERE TUOI <18 OR TUOI >65)
	BEGIN 
		RAISERROR (N'Tuổi phải từ 18 đến 65', 16, 1)
		ROLLBACK TRANSACTION 
		RETURN 
	END
END


CREATE TRIGGER NHANVIEN_UPDATE_CHECK
ON NHANVIEN
AFTER UPDATE
AS
BEGIN
	IF EXISTS (SELECT 1 FROM INSERTED WHERE DIACHI LIKE N'%TP HCM%')
	BEGIN
		RAISERROR (N'Không được cập nhật nhân viên ở TP HCM', 16, 1)
		ROLLBACK TRANSACTION
		RETURN 
	END
END

INSERT INTO NHANVIEN (MA_NHANVIEN, HO_NHANVIEN, TEN_NHANVIEN, GIOITINH, TUOI, DIACHI, TONGSO_DA)
VALUES
('NV001', 'Nguyen', 'An', 'Nam', 25, 'Hà Nội', 5),
('NV002', 'Tran', 'Binh', 'Nam', 30, 'Hồ Chí Minh', 7),
('NV003', 'Le', 'Hoa', 'Nữ', 22, 'Đà Nẵng', 3),
('NV004', 'Pham', 'Linh', 'Nữ', 28, 'Cần Thơ', 2),
('NV005', 'Do', 'Minh', 'Nam', 35, 'Hải Phòng', 6),
('NV006', 'Nguyen', 'Thao', 'Nữ', 24, 'Nha Trang', 4),
('NV007', 'Hoang', 'Long', 'Nam', 27, 'Huế', 5),
('NV008', 'Phan', 'Mai', 'Nữ', 26, 'Quảng Nam', 3),
('NV009', 'Bui', 'Khang', 'Nam', 29, 'Bình Định', 6),
('NV010', 'Dang', 'Trinh', 'Nữ', 23, 'Đồng Nai', 2),
('NV011', 'Vo', 'Quoc', 'Nam', 31, 'Vũng Tàu', 5),
('NV012', 'Cao', 'Nhi', 'Nữ', 21, 'Bạc Liêu', 1),
('NV013', 'Trieu', 'Dat', 'Nam', 32, 'Tây Ninh', 4),
('NV014', 'Ha', 'Luan', 'Nam', 33, 'Long An', 6),
('NV015', 'Ngo', 'Lan', 'Nữ', 27, 'Lâm Đồng', 3),
('NV016', 'La', 'Son', 'Nam', 29, 'Gia Lai', 5),
('NV017', 'Chu', 'My', 'Nữ', 26, 'Bình Dương', 4),
('NV018', 'Kim', 'Vinh', 'Nam', 28, 'Thanh Hóa', 5),
('NV019', 'Quach', 'Huong', 'Nữ', 25, 'Bến Tre', 3),
('NV020', 'Lu', 'Toan', 'Nam', 30, 'Trà Vinh', 6);

INSERT INTO NHANVIEN 
(MA_NHANVIEN, HO_NHANVIEN, TEN_NHANVIEN, GIOITINH, TUOI, DIACHI, TONGSO_DA, LUONG)
VALUES 
('NV021', N'Nguyễn Ánh', N'Dương', N'Nữ', 26, N'Hà Nội', 4, 20000);

INSERT INTO NHANVIEN 
(MA_NHANVIEN, HO_NHANVIEN, TEN_NHANVIEN, GIOITINH, TUOI, DIACHI, TONGSO_DA, LUONG)
VALUES 
('NV022', N'Nguyễn Minh', N'Tú', N'Nam', 29, N'Thái Bình', 3, 21000);

INSERT INTO NHANVIEN 
(MA_NHANVIEN, HO_NHANVIEN, TEN_NHANVIEN, GIOITINH, TUOI, DIACHI, TONGSO_DA, LUONG)
VALUES 
('NV023', N'Nguyễn Hoài', N'Phương', N'Nữ', 24, N'Nam Định', 3, 22000);

CREATE TRIGGER AFTERINSERT_NHANVIEN
ON NHANVIEN
AFTER INSERT
AS 
BEGIN
	DECLARE @SONAM INT, @SONU INT;

	SELECT @SONAM = COUNT(*) FROM NHANVIEN WHERE LTRIM(RTRIM(LOWER(GIOITINH))) COLLATE Vietnamese_CI_AI = N'nam';
	SELECT @SONU = COUNT (*) FROM NHANVIEN WHERE LTRIM(RTRIM(LOWER(GIOITINH))) COLLATE Vietnamese_CI_AI = N'nữ';

	PRINT N'Tổng số nhân viên Nam: ' + CAST ( @SONAM AS VARCHAR);
	PRINT N'Tổng số nhân viên Nữ: ' + CAST (@SONU AS VARCHAR);
END

SELECT DISTINCT GIOITINH FROM NHANVIEN;
UPDATE NHANVIEN
SET GIOITINH = N'Nữ'
WHERE GIOITINH = N'N?';

CREATE TRIGGER AFTERUPDATE_NHANVIEN
ON NHANVIEN
AFTER UPDATE
AS
BEGIN
	
	IF UPDATE(GIOITINH)
	BEGIN
		DECLARE @SONAM INT, @SONU INT;
		SELECT @SONAM = COUNT (*) FROM NHANVIEN WHERE LTRIM(RTRIM(LOWER(GIOITINH))) COLLATE Vietnamese_CI_AI = N'Nam';
		SELECT @SONU = COUNT (*) FROM NHANVIEN WHERE LTRIM(RTRIM(LOWER(GIOITINH))) COLLATE Vietnamese_CI_AI = N'Nữ';
		
		PRINT N'Tổng số nhân viên Nam: ' + CAST ( @SONAM AS VARCHAR);
		PRINT N'Tổng số nhân viên Nữ: ' + CAST (@SONU AS VARCHAR);
	END
END;

CREATE TRIGGER AFTERDELETE_NHANVIEN
ON NHANVIEN
AFTER DELETE
AS
BEGIN
	DECLARE @HOTEN_NV NVARCHAR(100),@SODA INT;

	SELECT @HOTEN_NV = HO_NHANVIEN +' ' + TEN_NHANVIEN,
		   @SODA = TONGSO_DA
	FROM deleted

	 PRINT N'Nhân viên "' + @HOTEN_NV + N'" đã thực hiện tổng cộng ' + CAST(@SODA AS VARCHAR) + N' đề án trước khi bị xóa.';
END;

DELETE FROM NHANVIEN
WHERE MA_NHANVIEN = 'NV023';

SELECT 
	NV.HO_NHANVIEN +' '+NV.TEN_NHANVIEN AS HOTEN_NHANVIEN
	CASE
		WHEN NV.LUONG < (SELECT AVG(NV2.LUONG)
						FROM NHANVIEN NV2
						WHERE NV2.MA_NHANVIEN = NV.MA_NHANVIEN)
FROM NHANVIEN NV
	
BEGIN TRY 
