CREATE DATABASE DAY10_B1

USE DAY10_B1

CREATE TABLE SANPHAM(
	MASP VARCHAR(5) NOT NULL,
	TENSP NVARCHAR(50) NOT NULL,
	GIA DECIMAL(18,0) NOT NULL,
	MOTA NVARCHAR(100)
)

ALTER TABLE SANPHAM
ADD CONSTRAINT PK_SANPHAM
PRIMARY KEY (MASP)

INSERT INTO SANPHAM (MASP, TENSP, GIA, MOTA)
VALUES 
('SP01', N'Chuột máy tính Logitech', 250000, N'Chuột không dây, thiết kế nhỏ gọn'),
('SP02', N'Bàn phím cơ Akko 3068', 1500000, N'Bàn phím cơ RGB, layout 68 phím'),
('SP03', N'Màn hình LG 24 inch', 3200000, N'Màn hình IPS Full HD, tần số 75Hz'),
('SP04', N'Tai nghe Sony WH-CH510', 1200000, N'Tai nghe bluetooth, pin 35 giờ'),
('SP05', N'USB Kingston 64GB', 180000, N'USB 3.0 tốc độ cao, vỏ kim loại'),
('SP06', N'Loa Bluetooth JBL Go 3', 990000, N'Chống nước IP67, âm thanh rõ nét'),
('SP07', N'Webcam Logitech C920', 2100000, N'Full HD 1080p, hỗ trợ ghi âm'),
('SP08', N'Ổ cứng SSD 500GB Samsung', 1700000, N'Tốc độ đọc ghi cao, SATA 3'),
('SP09', N'Sạc dự phòng Anker 20000mAh', 850000, N'Sạc nhanh PowerIQ, nhỏ gọn'),
('SP10', N'Máy in Canon LBP2900', 2950000, N'Máy in laser trắng đen, tiết kiệm mực');


CREATE NONCLUSTERED INDEX ID_GIA_SP
ON SANPHAM (GIA)

DROP INDEX ID_GIA_SP ON SANPHAM;

SELECT MASP, GIA 
FROM SANPHAM 
WHERE GIA = 1500000;

CREATE DATABASE DAY10_B2

USE DAY10_B2

CREATE TABLE DONHANG(
	MA_DH VARCHAR(5) NOT NULL,
	MA_KH VARCHAR(5) NOT NULL,
	NGAY_DATHANG DATE NOT NULL,
	TRANGTHAI NVARCHAR(20) NOT NULL
)

ALTER TABLE DONHANG
ADD CONSTRAINT PK_DONHANG
PRIMARY KEY (MA_DH)

INSERT INTO DONHANG (MA_DH, MA_KH, NGAY_DATHANG, TRANGTHAI)
VALUES 
('DH001', 'KH01', '2025-05-01', N'Chờ xác nhận'),
('DH002', 'KH02', '2025-05-01', N'Đã xác nhận'),
('DH003', 'KH03', '2025-05-02', N'Đang giao'),
('DH004', 'KH04', '2025-05-02', N'Hoàn thành'),
('DH005', 'KH05', '2025-05-03', N'Đã hủy'),
('DH006', 'KH01', '2025-05-03', N'Chờ xác nhận'),
('DH007', 'KH02', '2025-05-04', N'Đang giao'),
('DH008', 'KH03', '2025-05-04', N'Đã xác nhận'),
('DH009', 'KH06', '2025-05-05', N'Hoàn thành'),
('DH010', 'KH07', '2025-05-05', N'Đã hủy');

CREATE NONCLUSTERED INDEX ID_MAKH_TRANGTHAI
ON DONHANG (MA_KH, TRANGTHAI)

DROP INDEX ID_MAKH_TRANGTHAI ON DONHANG;

CREATE NONCLUSTERED INDEX ID_MAKH_TRANGTHAI
ON DONHANG (MA_KH, TRANGTHAI)
INCLUDE (MA_DH, NGAY_DATHANG);

SELECT MA_DH, NGAY_DATHANG
FROM DONHANG
WHERE MA_KH = 'KH01' AND TRANGTHAI = N'Chờ xác nhận';

CREATE DATABASE TRIGGER_DML_B1

USE TRIGGER_DML_B1

CREATE TABLE NHANVIEN (
    MANV VARCHAR(5) NOT NULL,
    HOTEN NVARCHAR(50) NOT NULL,
    GIOITINH NVARCHAR(3) NOT NULL,
    TUOI INT NOT NULL,
    LUONG DECIMAL(10,2) NOT NULL,
    THANHPHO NVARCHAR(30)
);

CREATE TABLE DEAN (
    MADE VARCHAR(5) NOT NULL,
    MANV VARCHAR(5) NOT NULL,
    TENDA NVARCHAR(50)
);

ALTER TABLE NHANVIEN
ADD CONSTRAINT PK_NHANVIEN
PRIMARY KEY (MANV)

ALTER TABLE DEAN
ADD CONSTRAINT PK_DEAN
PRIMARY KEY (MADE)

CREATE TRIGGER TRG_INSERTLUONG_THANHPHO_CK
ON NHANVIEN
INSTEAD OF INSERT
AS
BEGIN 
	IF EXISTS (SELECT 1 FROM INSERTED WHERE LUONG <=15000 OR TUOI < 18 OR TUOI >65)
	BEGIN 
		PRINT(N'Lỗi: Lương phải > 15000 và tuổi phải từ 18 đến 65.');
		ROLLBACK TRANSACTION;
	END

	ELSE
	BEGIN 
		INSERT INTO NHANVIEN (MANV, HOTEN, GIOITINH,TUOI,LUONG,THANHPHO)
		SELECT MANV,HOTEN,GIOITINH,TUOI,LUONG,THANHPHO
		FROM inserted;
	END

	IF EXISTS (SELECT 1 FROM inserted WHERE THANHPHO LIKE '%TP HCM%')
	BEGIN 
		PRINT (N'Không được cập nhật nhân viên ở TP HCM.')
		ROLLBACK TRANSACTION;
	END
	ELSE 
	BEGIN
		INSERT INTO NHANVIEN( MANV, HOTEN,GIOITINH,TUOI,LUONG,THANHPHO)
		SELECT MANV, HOTEN,GIOITINH,TUOI,LUONG,THANHPHO
		FROM inserted
	END
END;

DROP TRIGGER TRG_INSERTLUONG_CK

INSERT INTO NHANVIEN (MANV, HOTEN, GIOITINH, TUOI, LUONG, THANHPHO) VALUES
('NV01', 'Nguyen Van A', 'Nam', 30, 20000, 'HA NOI'),
('NV02', 'Tran Thi B', 'Nu', 25, 18000, 'Da Nang'),
('NV03', 'Le Van C', 'Nam', 45, 17000, 'Ha Noi'),
('NV04', 'Pham Thi D', 'Nu', 22, 16000, 'HA NOI'),  
('NV05', 'Do Van E', 'Nam', 64, 19000, 'Can Tho'),  
('NV06', 'Hoang Thi F', 'Nu', 35, 22000, 'Hue'),
('NV07', 'Nguyen Van G', 'Nam', 40, 15500, 'HA NOI'),
('NV08', 'Pham Thi H', 'Nu', 29, 17000, 'Da Nang'),
('NV09', 'Le Van I', 'Nam', 18, 18000, 'Ha Noi'),
('NV10', 'Tran Thi J', 'Nu', 65, 16000, 'HA NOI');

DELETE FROM NHANVIEN


INSERT INTO DEAN (MADE, MANV, TENDA) VALUES
('DA01', 'NV01', 'Du an CRM'),
('DA02', 'NV02', 'Du an WebApp'),
('DA03', 'NV01', 'Du an IoT'),
('DA04', 'NV04', 'Du an Blockchain'),
('DA05', 'NV06', 'Du an HRM'),
('DA06', 'NV07', 'Du an Kế Toán'),
('DA07', 'NV06', 'Du an Marketing'),
('DA08', 'NV03', 'Du an AI'),
('DA09', 'NV10', 'Du an Big Data'),
('DA10', 'NV02', 'Du an Mobile App');

CREATE DATABASE TRIGGER_DML_B2

USE TRIGGER_DML_B2

CREATE TABLE NHANVIEN (
    MANV VARCHAR(5) NOT NULL,
    HOTEN NVARCHAR(50) NOT NULL,
    GIOITINH NVARCHAR(3) NOT NULL,
    TUOI INT NOT NULL,
    LUONG DECIMAL(10,2) NOT NULL,
    THANHPHO NVARCHAR(30) NOT NULL,
	SO_DA INT NOT NULL
);

DROP TABLE NHANVIEN

ALTER TABLE NHANVIEN
ADD CONSTRAINT PK_NHANVIEN	
PRIMARY KEY (MANV)

INSERT INTO NHANVIEN (MANV, HOTEN, GIOITINH, TUOI, LUONG, THANHPHO, SO_DA) VALUES
('NV01', N'Nguyễn Văn A', N'Nam', 30, 20000, N'TP HCM', 3),
('NV02', N'Trần Thị B', N'Nữ', 25, 18000, N'Đà Nẵng', 2),
('NV03', N'Lê Văn C', N'Nam', 45, 17000, N'Hà Nội', 1),
('NV04', N'Phạm Thị D', N'Nữ', 22, 16000, N'TP HCM', 4),
('NV05', N'Đỗ Văn E', N'Nam', 64, 19000, N'Cần Thơ', 2),
('NV06', N'Hoàng Thị F', N'Nữ', 35, 22000, N'Huế', 5),
('NV07', N'Nguyễn Văn G', N'Nam', 40, 15500, N'TP HCM', 2),
('NV08', N'Phạm Thị H', N'Nữ', 29, 17000, N'Đà Nẵng', 3),
('NV09', N'Lê Văn I', N'Nam', 18, 15500, N'Hà Nội', 1),
('NV10', N'Trần Thị J', N'Nữ', 65, 16000, N'TP HCM', 0);

SELECT * FROM NHANVIEN

CREATE TRIGGER TRG_COUNT_NAM_NU
ON NHANVIEN
AFTER INSERT
AS 
BEGIN
	DECLARE @SONAM INT, @SONU INT;
	SELECT @SONAM = COUNT (*) FROM NHANVIEN WHERE GIOITINH =N'Nam'
	SELECT @SONU = COUNT (*) FROM NHANVIEN WHERE GIOITINH = N'Nữ'

	PRINT N'Tổng số nhân viên Nam: ' + CAST (@SONAM AS VARCHAR);
	PRINT N'Tổng số nhân viên Nu:' + CAST (@SONU AS VARCHAR);
END;

INSERT INTO NHANVIEN (MANV, HOTEN, GIOITINH, TUOI, LUONG, THANHPHO, SO_DA)
VALUES ('NV11', N'Ngô Thị K', N'Nữ', 28, 17500, N'Hải Phòng', 2);

INSERT INTO NHANVIEN (MANV, HOTEN, GIOITINH, TUOI, LUONG, THANHPHO, SO_DA)
VALUES ('NV12', N'Phạm Văn L', N'Nam', 32, 21000, N'Quảng Ninh', 1);

INSERT INTO NHANVIEN (MANV, HOTEN, GIOITINH, TUOI, LUONG, THANHPHO, SO_DA)
VALUES ('NV13', N'Nguyễn Thị M', N'Nữ', 27, 18500, N'Bình Dương', 3);

CREATE TRIGGER TRG_COUNT_NAM_NU_UPDATE
ON NHANVIEN
AFTER UPDATE
AS
BEGIN
	IF UPDATE (GIOITINH)
	BEGIN
		DECLARE @SONAM INT, @SONU INT;
		SELECT @SONAM = COUNT (*) FROM NHANVIEN WHERE GIOITINH =N'Nam'
		SELECT @SONU = COUNT (*) FROM NHANVIEN WHERE GIOITINH = N'Nữ'

		PRINT N'Tổng số nhân viên Nam: ' + CAST (@SONAM AS VARCHAR);
		PRINT N'Tổng số nhân viên Nu:' + CAST (@SONU AS VARCHAR);
	END
END;

UPDATE NHANVIEN
SET GIOITINH = N'Nam'
WHERE MANV = 'NV13';

CREATE TRIGGER TRG_COUNT_DEAN_DELETE
ON NHANVIEN
AFTER DELETE
AS
BEGIN
	DECLARE @HOTEN NVARCHAR(100), @DEAN INT;

	SELECT TOP 1 
		@HOTEN = HOTEN, 
		@DEAN = SO_DA
	FROM deleted;

	PRINT N'Nhân viên: ' + @HOTEN + N' đã thực hiện tổng ' 
		+ CAST(@DEAN AS VARCHAR) + N' trước khi bị xóa';
END;

