CREATE DATABASE QLY_DUAN1

USE QLY_DUAN1

CREATE TABLE CHUC_VU (
	MA_CHUCVU VARCHAR(5) NOT NULL,
	TEN_CHUCVU NVARCHAR(20) NOT NULL,
	MOTA NVARCHAR(100)
)

CREATE TABLE PHONG_BAN(
	MA_PB VARCHAR(5) NOT NULL,
	TEN_PB NVARCHAR(20) NOT NULL,
	MOTA NVARCHAR(20)
)

CREATE TABLE NHANVIEN (
	MA_NV VARCHAR(5) NOT NULL,
	HO_NV NVARCHAR(20) NOT NULL,
	TEN_NV NVARCHAR(50) NOT NULL,
	DIA_CHI NVARCHAR(150) NOT NULL,
	SDT INT,
	MA_PB VARCHAR(5),
	MA_CHUCVU VARCHAR(5),
)

CREATE TABLE DA(
	MA_DA VARCHAR(5) NOT NULL,
	TEN_DA NVARCHAR(50),
	NGAY_KHOI_CONG DATE,
	NGAY_KET_THUC DATE,
	MOTA NVARCHAR(100),
)

CREATE TABLE CTDA (
	MA_NV VARCHAR(5) NOT NULL,
	MA_DA VARCHAR(5) NOT NULL,
	MOTA NVARCHAR(100),
)


ALTER TABLE DA
ADD CONSTRAINT PK_MA_DA
PRIMARY KEY (MA_DA)


ALTER TABLE CTDA
ADD CONSTRAINT PK_CTDA
PRIMARY KEY (MA_DA,MA_NV)

ALTER TABLE NHANVIEN 
ADD GIOITINH VARCHAR(10) 

ALTER TABLE NHANVIEN
ADD LUONG INT

ALTER TABLE NHANVIEN
DROP COLUMN GIOITINH

ALTER TABLE NHANVIEN
ADD CONSTRAINT CHK_LUONG
CHECK (LUONG > 5000)

ALTER TABLE CHUC_VU
ADD CONSTRAINT PK_MA_CV
PRIMARY KEY (MA_CHUCVU)

ALTER TABLE PHONG_BAN
ADD CONSTRAINT PK_MACV
PRIMARY KEY (MA_PB)

ALTER TABLE NHANVIEN
ADD CONSTRAINT PK_MANV
PRIMARY KEY (MA_NV)

ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_MANV
FOREIGN KEY(MA_PB) REFERENCES PHONG_BAN (MA_PB)

ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_MACV
FOREIGN KEY (MA_CHUCVU) REFERENCES CHUC_VU (MA_CHUCVU)

CREATE TABLE CHUCVU (
	MA_CV VARCHAR(5) NOT NULL,
	MA_NV VARCHAR(5) NOT NULL,
	TEN_CV NVARCHAR(50) NOT NULL,
	NGAY_NHAM_CHUC DATE NOT NULL,
	MOTA NVARCHAR(50),
)

ALTER TABLE NHAN_VIEN
ADD CONSTRAINT NHAN_VIEN_UNQ_EMAIL
UNIQUE (EMAIL) 

ALTER TABLE NHAN_VIEN
DROP CONSTRAINT NHAN_VIEN_UNQ_EMAIL;
